Update V03.06.09-FW18

diff --git a/projectroot/etc/config-tools/config_ethernet b/projectroot/etc/config-tools/config_ethernet
--- a/projectroot/etc/config-tools/config_ethernet
+++ b/projectroot/etc/config-tools/config_ethernet
@@ -3,7 +3,7 @@
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 #
-# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG
+# Copyright (c) 2018-2020 WAGO Kontakttechnik GmbH & Co. KG
 
 #-----------------------------------------------------------------------------#
 # Script-name: config_ethernet
@@ -14,37 +14,30 @@
 #-----------------------------------------------------------------------------#
 
 # load general definitions and functions
-if [ ! -f "/etc/config-tools/config_tool_defines" ]; then
-  echo "config_tool_defines missing"
-  exit 255
+if [[ ! -f "/etc/config-tools/config_tool_lib" ]]; then
+  echo "config_tool_lib missing"
+  exit 64
 fi
 
-. /etc/config-tools/config_tool_defines
+. /etc/config-tools/config_tool_lib
 
 status=$SUCCESS
 
-set_interface_config () {
-  local json_config="$1"
-  out=$(dbus-send --system --print-reply --reply-timeout=15000 --type=method_call --dest=de.wago.netconfd /de/wago/netconfd/interface_config de.wago.netconfd1.interface_config.setinterfaceconfig string:"${json_config}")
-  for token in $out; do 
-      dbus_out=$token
-  done  
-  dbus_out=${dbus_out#\"}
-  dbus_out=${dbus_out%\"}  
-  echo "$dbus_out"
-}
+if [[ $# -lt 1 ]]; then
+    exit 1
+fi
 
 # show help-text if requested
-if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
   echo
   echo "* Change the ethernet port settings *"
   echo
   echo "Usage: $0 < [interface=interface-value] port=port-value [state=state-value ] [ autoneg=autoneg-value ] [ speed=speed-value ] [duplex=duplex-value ]"
-  echo "With autoneg=on, no speed or duplex values have to be provided."
+  echo "With autoneg=enabled, no speed or duplex values have to be provided."
   echo
 # pfc200-specific settings
   echo "interface-value: eth0 [ignored]"
-  echo "port-value: $(/etc/config-tools/get_eth_config --print-ports)"
+  echo "port-value: $(GetPorts)"
   echo "state-value: enabled/disabled"
   echo "autoneg-value: enabled/disabled"
   echo "speed-value: 10M/100M"
@@ -55,6 +48,18 @@ fi
 
 declare -A params
 
+function is_supported_port {
+    value=$1
+
+    for port in $(GetPorts); do
+        if [[ "$value" == "$port" ]]; then
+            return 0
+        fi
+    done
+
+    return 1
+}
+
 while [[ $# -ne 0 ]]; do
     case "$1" in
         interface=*)
@@ -62,38 +67,36 @@ while [[ $# -ne 0 ]]; do
         port=*)
             port=${1#port=}
             params[device]="\"$port\""
+            if ! is_supported_port $port; then
+                status=${CONFIG_DATA_ERROR}
+            fi
             ;;
         state=*)
-
-            if [[ "${1#state=}" == "on" || "${1#state=}" == "enabled" ]]; then
-                state="up"
-            elif [[ "${1#state=}" == "off" || "${1#state=}" == "disabled" ]]; then
-                state="down"
-            else
-                state="${1#state=}"
+            value=${1#state=}
+            if [[ "$value" == "on" || "$value" == "enabled" ]]; then
+                value="up"
+            elif [[ "$value" == "off" || "$value" == "disabled" ]]; then
+                value="down"
             fi
-            params[state]="\"$state\""
+            params[state]="\"$value\""
             ;;
         autoneg=*)
-
-            if [[ "${1#autoneg=}" == "on" || "${1#autoneg=}" == "enabled" ]]; then
-                autoneg=true
-            elif [[ "${1#autoneg=}" == "off" || "${1#autoneg=}" == "disabled" ]]; then
-                autoneg=false
-            else
-                autoneg=${1#autoneg=}
+            value=${1#autoneg=}
+            if [[ "$value" == "on" || "$value" == "enabled" ]]; then
+                value="on"
+            elif [[ "$value" == "off" || "$value" == "disabled" ]]; then
+                value="off"
             fi
-            params[autonegotiation]="$autoneg"
+            params[autonegotiation]="\"$value\""
             ;;
         speed=*)
-            if [[ "${1#speed=}" == "10M" ]]; then
-                speed=10
-            elif [[ "${1#speed=}" == "100M" ]]; then
-                speed=100
-            else
-                speed="${1#speed=}"
+            value=${1#speed=}
+            if [[ "$value" == "10M" ]]; then
+                value=10
+            elif [[ "$value" == "100M" ]]; then
+                value=100
             fi
-            params[speed]=$speed
+            params[speed]=$value
             ;;
         duplex=*)
             params[duplex]="\"${1#duplex=}\""
@@ -112,13 +115,13 @@ if [[ $status == $SUCCESS ]]; then
     json_content=""
     for i in "${!params[@]}" ; do
         if [[ $add_separator == false ]]; then
-                json_content="\"$i\":${params[$i]}"
-                add_separator=true
+            json_content="\"$i\":${params[$i]}"
+            add_separator=true
         else
-                json_content="$json_content,\"$i\":${params[$i]}"
+            json_content="$json_content,\"$i\":${params[$i]}"
         fi
-    done    
-    set_interface_config "{${json_content}}"
+    done
+    $NETWORK_CONFIG --interface-config --set "{${json_content}}" --format=json --quiet
     status=$?
 fi
 
diff --git a/projectroot/etc/config-tools/config_tool_lib b/projectroot/etc/config-tools/config_tool_lib
--- a/projectroot/etc/config-tools/config_tool_lib
+++ b/projectroot/etc/config-tools/config_tool_lib
@@ -1,10 +1,4 @@
 #!/bin/bash
-# This Source Code Form is subject to the terms of the Mozilla Public
-# License, v. 2.0. If a copy of the MPL was not distributed with this
-# file, You can obtain one at http://mozilla.org/MPL/2.0/.
-#
-# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG
-
 #-----------------------------------------------------------------------------#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
@@ -12,7 +6,7 @@
 #
 # This file is part of PTXdist package config-tools.
 #
-# Copyright (c) 2008-2019 WAGO Kontakttechnik GmbH & Co. KG
+# Copyright (c) 2008-2020 WAGO Kontakttechnik GmbH & Co. KG
 #-----------------------------------------------------------------------------#
 #-----------------------------------------------------------------------------#
 # Script:   config_tool_lib
@@ -25,6 +19,8 @@
 # Author:   PEn: WAGO Kontakttechnik GmbH & Co. KG
 # Author:   MLa: WAGO Kontakttechnik GmbH & Co. KG
 # Author:   OG:  WAGO Kontakttechnik GmbH & Co. KG
+# Author:   MSc: WAGO Kontakttechnik GmbH & Co. KG
+# Author:   MOe: WAGO Kontakttechnik GmbH & Co. KG
 #-----------------------------------------------------------------------------#
 
 #bash "include guard"
@@ -459,8 +455,8 @@ report_start()
 #-----------------------------------------------------------------------------#
 report_end()
 {
+    local IS_ARRAY="${1:-"false"}"
     local RESULT=0
-    IS_ARRAY="${1:-"false"}"
 
     # Close JSON part if any content present
     if [ -n "$JSON_REPORT" ]; then 
@@ -482,10 +478,13 @@ report_end()
 
 # Function to add report content (structured output on stdout)
 # as key/value pair.
+# This function requires availability of variables "TEXTOUT" and "JSONOUT",
+# which have to be provided (0: no output, integer value != 0: output requested).
 #
 # Param 1: Key for content to add
 # Param 2: Content value to add
-# Param 3: Value format character (s)tring, (i)nt; optional, default is string
+# Param 3: Value format character (s)tring, (i)nt, (b)ool; optional, default is string
+# Param 4: Skip key name for text output; optional
 #
 # Return: 0 on success, unequal to 0 otherwise,
 #         INVALID_PARAMETER on invalid parameter combination (e.g. format)
@@ -498,6 +497,7 @@ report()
     local REPORT_KEY="$1"
     local REPORT_VALUE="$2"
     local REPORT_VALUE_FORMAT="${3:-}"
+    local SKIP_KEY_NAME=${4:-false}
 
     # Set default if no parameter given for format
     if [ -z "$REPORT_VALUE_FORMAT" ]; then
@@ -505,7 +505,10 @@ report()
     fi
 
     # Check for plausible parameters
-    if [[ "$REPORT_VALUE_FORMAT" == "i" && ! $REPORT_VALUE =~ ^[-+]?[0-9]+$ ]]; then
+    if [[ "$REPORT_VALUE_FORMAT" == "i" && ! "$REPORT_VALUE" =~ ^[-+]?[0-9]+$ ]]; then
+        return $INVALID_PARAMETER
+    fi
+    if [[ "$REPORT_VALUE_FORMAT" == "b" && "$REPORT_VALUE" != "true" && "$REPORT_VALUE" != "false" ]]; then
         return $INVALID_PARAMETER
     fi
 
@@ -514,7 +517,10 @@ report()
         if [ -n "$TEXT_REPORT" ]; then
             TEXT_REPORT="${TEXT_REPORT}\n"
         fi
-        TEXT_REPORT="${TEXT_REPORT}${REPORT_KEY}=${REPORT_VALUE}"
+        if ! $SKIP_KEY_NAME; then
+            TEXT_REPORT="${TEXT_REPORT}${REPORT_KEY}="
+        fi
+        TEXT_REPORT="${TEXT_REPORT}${REPORT_VALUE}"
     fi
 
     # Add JSON output if requested
@@ -531,6 +537,12 @@ report()
             local JSON_ESCAPED_VALUE
             JSON_ESCAPED_VALUE="$(escape_json "$REPORT_VALUE")"
             JSON_REPORT="${JSON_REPORT} ${JSON_ESCAPED_VALUE}"
+        elif [ "$REPORT_VALUE_FORMAT" == "b" ]; then
+            if ${REPORT_VALUE}; then
+                JSON_REPORT="${JSON_REPORT} true"
+            else
+                JSON_REPORT="${JSON_REPORT} false"
+            fi
         else
             JSON_REPORT="${JSON_REPORT} ${REPORT_VALUE}"
         fi
@@ -541,6 +553,8 @@ report()
 
 # Function to add report content (structured output on stdout)
 # either as JSON array or as text.
+# This function requires availability of variables "TEXTOUT" and "JSONOUT",
+# which have to be provided (0: no output, integer value != 0: output requested).
 #
 # Param 1: Content value to add
 # Param 2: Value format character (s)tring, (i)nt; optional, default is string
@@ -1052,12 +1066,14 @@ ReportError()
 SetLastError()
 {
   local errorText="$*"
+  local errorFile="$(mktemp)"
 
   print_dbg "SetLastError: ${errorText}"
 
-  echo -n "$errorText" > "${LAST_ERROR_FILENAME}.tmp" &&
-    chgrp www "${LAST_ERROR_FILENAME}.tmp" &&
-    mv "${LAST_ERROR_FILENAME}.tmp" "${LAST_ERROR_FILENAME}"
+  echo -n "$errorText" > "${errorFile}" &&
+    chmod 0640 "${errorFile}" &&
+    chgrp www "${errorFile}" &&
+    mv "${errorFile}" "${LAST_ERROR_FILENAME}"
 }
 
 # search for a specified parameter in the parameter-list
@@ -1391,15 +1407,18 @@ function GetTargetName
   # legacy
   else
     order="$(/etc/config-tools/get_typelabel_value ORDER)"
-    prefix="${order:0:3}"
+    order3="${order:0:3}"
+    order5="${order:0:5}"
     order="${order:4:2}"
 
     if [ "${order}" == "81" ]; then
       product="PFC100"
     elif [ "${order}" == "82" ]; then
       product="PFC200"
-    elif [ "${prefix}" == "762" ]; then
+    elif [ "${order3}" == "762" ]; then
       product="TP600"
+    elif [ "${order5}" == "752-8" ]; then
+      product="EC752"
     fi
   fi
 
@@ -1429,6 +1448,46 @@ function CheckEncryptionPassphrase
   fi
 
   return $status
+}
+
+#-----------------------------------------------------------------------------#
+function GetBridgeConfig {
+  echo $($NETWORK_CONFIG --get --bridge-config --quiet)
+}
+
+#-----------------------------------------------------------------------------#
+function GetInterfaceConfig {
+  echo $($NETWORK_CONFIG --get --interface-config --quiet)
+}
+
+#-----------------------------------------------------------------------------#
+function GetPorts {
+  for port in $(GetInterfaceConfig); do
+    if [[ $port == device* ]]; then
+      echo -n "${port##device=} "
+    fi
+  done
+}
+
+#-----------------------------------------------------------------------------#
+function GetBridges {
+  for bridge in $(GetBridgeConfig); do
+    echo "${bridge%%=*} "
+  done
+}
+
+#-----------------------------------------------------------------------------#
+function GetLegacyPorts {
+  local ports=""
+  for bridge in $(GetBridges); do
+    if [ $bridge == "br0" ]; then
+        ports="$ports X1"
+    elif [ $bridge == "br1" ]; then
+        ports="$ports X2"
+    fi
+  done
+
+  echo $ports
 }
 
 #### Begin D3I Implementation #######
